# This is a part of the Sleex's compositor user configuration
# You can put custom rules here
# https://nferhat.github.io/fht-compositor/configuration/window-rules.html
# https://nferhat.github.io/fht-compositor/configuration/layer-rules.html